version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/backend"
      - "/frontend"
      - "/services/reis"
      - "/dev/caddy-gateway-proxy"
      - "/dev/mcp-tool-as-server"
      - "/dev/oauth-mock"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"

  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "/dev/postgres"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/backend"
      - "/e2e"
      - "/frontend"
    schedule:
      interval: "daily"
    groups:
      ai-sdk:
        patterns:
          - "ai"
          - "@ai-sdk/*"
          - "ollama-ai-provider-v2"
      mantine:
        patterns:
          - "mantine-"
          - "@mantine/*"
      nestjs:
        patterns:
          - "nest-*"
          - "nestjs-*"
          - "@nestjs/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
      testcontainers:
        patterns:
          - "testcontainers"
          - "@testcontainers/*"
      vite:
        patterns:
          - "vite"
          - "*/vite"
          - "@vitejs/*"
          - "vitest"
          - "@vitest/*"

  - package-ecosystem: "uv"
    directories:
      - "/services/reis"
      - "/services/confluence-importer"
    schedule:
      interval: "daily"
    groups:
      langchain:
        patterns:
          - "langchain-*"
      pytest:
        patterns:
          - "pytest*"
      pydantic:
        patterns:
          - "pydantic*"
