allow_licenses:
  - 'Apache-2.0'
  - 'BlueOak-1.0.0'
  - '0BSD'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'CC-BY-3.0'
  - 'CC-BY-SA-3.0'
  - 'CC-BY-SA-4.0'
  - 'FTL'
  - 'ISC'
  - 'JSON'
  - 'MIT'
  - 'MIT-0'
  - 'MIT-CMU'
  - 'MPL-1.1'
  - 'MPL-2.0'
  - 'PSF-2.0'
  - 'Python-2.0'
  - 'CNRI-Python'
  - 'LGPL-2.1'
  - 'LGPL-2.1-or-later'
  - 'LGPL-2.1-only'
  - 'Unlicense'
  - 'CC0-1.0'
  - 'OFL-1.1'
  - 'Zlib'
  - 'ZPL-2.1'
allow-dependencies-licenses:
  - 'pkg:pypi/structlog' # This package is a false-positive because of a Contributor License Agreement, which is not a software license.
  - 'pkg:pypi/azure-core' # This package is a false-positive because of a Contributor License Agreement, which is not a software license.
  - 'pkg:pypi/azure-core' # This package is a false-positive because of a Contributor License Agreement, which is not a software license.
  - 'pkg:pypi/pyphen' # This package is a false-positive because it is GPL or LGPL or MPL (not "and").
  - 'pkg:pypi/docutils' # Docutils is mostly public domain. The one file under GPL is not used here and should therefore not apply. See also https://docutils.sourceforge.io/0.7/COPYING.html
  - 'pkg:pypi/fastapi-cloud-cli' # False positive, is MIT
  - 'pkg:pypi/aiohttp' # False positive, is Apache-2.0
  - 'pkg:pypi/langsmith' # False positive, is MIT
  - 'pkg:npm/@n8n/json-schema-to-zod' # False positive, is ISC for this part of a large repository
  - 'pkg:npm/sql-highlight' # False positive, is MIT
  - 'pkg:pypi/pypdf' # False positive, is free license
  - 'pkg:pypi/aiohappyeyeballs' # False positive
  - 'pkg:pypi/msal-extensions' # False positive because of a Contributor License Agreement
  - 'pkg:pypi/pillow' # False positive because of addition to MIT-CMU license, but still free
  - 'pkg:pypi/python-dateutil' # False positive, is Apache
  - 'pkg:pypi/pytz' # False positive, is Apache
  - 'pkg:pypi/psycopg-binary' # False positive, is LGPL-3.0-only
  - 'pkg:pypi/jaraco-classes' # False positive, is MIT
  - 'pkg:pypi/jaraco-context' # False positive, is MIT
  - 'pkg:pypi/jaraco-functools' # False positive, is MIT
  - 'pkg:pypi/pydocket' # False positive, is MIT
  - 'pkg:pypi/typing-extensions' # False positive, it is PSF
