name: Frontend
permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/frontend.yaml
      - frontend/**
  workflow_call:

defaults:
  run:
    working-directory: frontend

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm install
      - run: npm run build

  frontend-check-generated-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run generate-api
      - run: git add -N .
      - run: git diff .
      # exits with exitcode != 0 if changes are detected
      - run: git diff --quiet .

  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm install
      - run: npm run lint
      - run: npm run find-unused-resources

  frontend-test:
    runs-on: ubuntu-latest
    env:
      VITE_SERVER_URL: http://localhost:5173/api-proxy
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm install
      - run: npm test
