name: Release Notification
permissions:
  contents: read

on:
  release:
    types:
      - created

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    steps:
      - name: Notify Slack on Releases
        uses: amendx/slackbot-release@1.0.1
        with:
          slack_webhook_url: ${{ secrets.SLACK_RELEASE_WEBHOOK_URL }}